# attogram/shared-media-api - codeclimate.yml - v0.9.1
exclude_paths:
- "vendor/"
engines:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR1,PSR2"
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess: # allow Object::method()
        enabled: false
      Controversial/Superglobals: # allow $_GET in sandbox
        enabled: false
      Design/DevelopmentCodeFragment: # allow print_r()
        enabled: false
  phan:
    enabled: true
    checks:
      PhanTypeMismatchArgument:
        enabled: false
      PhanTypeMismatchProperty:
        enabled: false
      PhanUndeclaredClassCatch:
        enabled: false
      PhanUndeclaredClassConstant:
        enabled: false
      PhanUndeclaredClassInstanceof:
        enabled: false
      PhanUndeclaredClassMethod:
        enabled: false
      PhanUndeclaredTypeParameter:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
        php:
          mass_threshold: 40
  csslint:
    enabled: true
  stylelint:
    enabled: true 
  fixme:
    enabled: true
  git-legal:
    enabled: true
ratings:
  paths:
  - "**.php"
  - "**.css"
  - "composer.json"
