language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly
  - hhvm
  
matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm

before_script:
  - if [ $TRAVIS_PHP_VERSION = "5.5" ]; then composer install --no-dev --ignore-platform-reqs; fi
  - if [ $TRAVIS_PHP_VERSION = "5.6" ]; then composer install --no-dev --ignore-platform-reqs; fi
  - if [ $TRAVIS_PHP_VERSION = "7.0" ]; then composer install --no-dev --ignore-platform-reqs; fi
  - if [ $TRAVIS_PHP_VERSION = "7.1" ]; then composer install --no-dev; fi
  - if [ $TRAVIS_PHP_VERSION = "7.2" ]; then composer install --no-dev; fi
  - if [ $TRAVIS_PHP_VERSION = "nightly" ]; then composer install --no-dev; fi
  - if [ $TRAVIS_PHP_VERSION = "hhvm" ]; then composer install --no-dev --ignore-platform-reqs; fi

script:
  - find src/ web/ tests/ -type f -name '*.php' -exec php -l {} \;
  - if [ $TRAVIS_PHP_VERSION = "7.0" ]; then phpunit; fi
  - if [ $TRAVIS_PHP_VERSION = "7.1" ]; then phpunit; fi
  - if [ $TRAVIS_PHP_VERSION = "7.2" ]; then phpunit; fi
  - if [ $TRAVIS_PHP_VERSION = "nightly" ]; then phpunit; fi
