# Attogram Shared Media API - https://github.com/attogram/shared-media-api
# Travis CI - https://travis-ci.org/attogram/shared-media-api
language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
matrix:
  fast_finish: true
before_script:
  - composer install
script:
  - if find docs/   -name "*.php" -exec php -l {} 2>&1 \; | grep "error,"; then exit 1; fi;
  - if find public/ -name "*.php" -exec php -l {} 2>&1 \; | grep "error,"; then exit 1; fi;
  - if find src/    -name "*.php" -exec php -l {} 2>&1 \; | grep "error,"; then exit 1; fi;
  - if find tests/  -name "*.php" -exec php -l {} 2>&1 \; | grep "error,"; then exit 1; fi;
  - if find vendor/ -name "*.php" -exec php -l {} 2>&1 \; | grep "error,"; then exit 1; fi;
  - if [ $TRAVIS_PHP_VERSION == "5.5" ]; then composer require phpunit/phpunit ~4; fi
  - if [ $TRAVIS_PHP_VERSION == "5.6" ]; then composer require phpunit/phpunit ~5; fi
  - if [ $TRAVIS_PHP_VERSION == "7.0" ]; then composer require phpunit/phpunit ~6; fi
  - if [ $TRAVIS_PHP_VERSION == "7.1" ]; then composer require phpunit/phpunit ~7; fi
  - if [ $TRAVIS_PHP_VERSION == "7.2" ]; then composer require phpunit/phpunit ~8; fi
  - if [ $TRAVIS_PHP_VERSION == "7.3" ]; then composer require phpunit/phpunit ~9; fi
  - if [ $TRAVIS_PHP_VERSION == "7.4" ]; then composer require phpunit/phpunit ~9; fi
  - vendor/bin/phpunit;
