# attogram/shared-media-api - .travis.yml - v0.10.12

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - composer install --no-dev
  - phpunit --version

script:
  - if find docs/ -name "*.php" -exec php -l {} 2>&1 \; | grep "error,"; then exit 1; fi;
  - if find public/ -name "*.php" -exec php -l {} 2>&1 \; | grep "error,"; then exit 1; fi;
  - if find src/ -name "*.php" -exec php -l {} 2>&1 \; | grep "error,"; then exit 1; fi;
  - if find tests/ -name "*.php" -exec php -l {} 2>&1 \; | grep "error,"; then exit 1; fi;
  - if [ $TRAVIS_PHP_VERSION == "5.5" ]; then composer require phpunit/phpunit ~4.8.36; vendor/bin/phpunit; else phpunit; fi
