# attogram/shared-media-api - .travis.yml - v0.10.2

language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly
  - 5.6
  - 5.5
  
matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: 5.6
    - php: 5.5

before_script:
  - composer install
  - phpunit --version
  #- vendor/bin/phpunit --version
  
script:
  - if find docs/ -name "*.php" -exec php -l {} 2>&1 \; | grep "syntax error, unexpected"; then exit 1; fi;
  - if find public/ -name "*.php" -exec php -l {} 2>&1 \; | grep "syntax error, unexpected"; then exit 1; fi;
  - if find src/ -name "*.php" -exec php -l {} 2>&1 \; | grep "syntax error, unexpected"; then exit 1; fi;
  - if find tests/ -name "*.php" -exec php -l {} 2>&1 \; | grep "syntax error, unexpected"; then exit 1; fi;
  #- vendor/bin/phpunit
  - phpunit
