language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly
  
matrix:
  fast_finish: true
  allow_failures:
    - php: 5.5
    - php: nightly

before_script:
  - if [ $TRAVIS_PHP_VERSION = "5.5" ]; then composer install --no-dev --ignore-platform-reqs; fi
  - if [ $TRAVIS_PHP_VERSION = "5.6" ]; then composer install --no-dev --ignore-platform-reqs; fi
  - if [ $TRAVIS_PHP_VERSION = "7.0" ]; then composer install --no-dev; fi
  - if [ $TRAVIS_PHP_VERSION = "7.1" ]; then composer install --no-dev; fi
  - if [ $TRAVIS_PHP_VERSION = "7.2" ]; then composer install --no-dev; fi
  - if [ $TRAVIS_PHP_VERSION = "nightly" ]; then composer install --no-dev; fi

script:
  - if find . -name "*.php" -exec php -l {} 2>&1 \; | grep "syntax error, unexpected"; then exit 1; fi
